#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/create_postgresql_users
- name: Refresh repos
  become: true
  ansible.builtin.apt:
    update_cache: true
- name: Installing postgres
  become: true
  ansible.builtin.package:
    name: postgresql
    state: present

- name: Allow remote connection
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postgresql/15/main/postgresql.conf
    line: "listen_addresses = '{{ postgres_server }}'"

- name: Set password encryption method
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postgresql/15/main/postgresql.conf
    line: 'password_encryption = scram-sha-256'

- name: Allow remote connection
  loop: "{{ schemes }}"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postgresql/15/main/pg_hba.conf
    line: "host {{ item.name }} {{item.username}} {{ postgres_server }}/24 scram-sha-256"
- name: Installing python3-psycopg2
  become: true
  ansible.builtin.package:
    name: python3-psycopg2
    state: present

- name: Restarting postgres
  become: true
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: true

- name: Creating database
  become: true
  become_user: "postgres"
  loop: "{{ schemes }}"
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    encoding: 'UTF-8'
    login_unix_socket: "/var/run/postgresql"
    state: present

- name: Creating user
  loop: "{{ schemes }}"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_user:
    db: "{{ item.name }}"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    login_unix_socket: "/var/run/postgresql"
    state: present

- name: Setting user's privileges on tables
  loop: "{{ schemes }}"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_privs:
    database: "{{ item.name }}"
    role: "{{ item.username }}"
    type: "table"
    privs: "ALL"
    objs: "ALL_IN_SCHEMA"
    login_unix_socket: "/var/run/postgresql"
    state: present

- name: Setting user's privileges on sequences
  loop: "{{ schemes }}"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_privs:
    database: "{{ item.name }}"
    role: "{{ item.username }}"
    type: "sequence"
    privs: "ALL"
    objs: "ALL_IN_SCHEMA"
    login_unix_socket: "/var/run/postgresql"
    state: present

- name: Setting user's privileges on functions
  loop: "{{ schemes }}"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_privs:
    database: "{{ item.name }}"
    role: "{{ item.username }}"
    type: "function"
    privs: "ALL"
    objs: "ALL_IN_SCHEMA"
    login_unix_socket: "/var/run/postgresql"
    state: present

- name: Setting user's privileges on procedures
  loop: "{{ schemes }}"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_privs:
    database: "{{ item.name }}"
    role: "{{ item.username }}"
    type: "procedure"
    privs: "ALL"
    objs: "ALL_IN_SCHEMA"
    login_unix_socket: "/var/run/postgresql"
    state: present

- name: Set default privileges on objects
  loop: "{{ schemes }}"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_privs:
    database: "{{ item.name }}"
    objs: ALL_DEFAULT
    privs: ALL
    type: default_privs
    role: "{{ item.username }}"
    grant_option: true
    login_unix_socket: "/var/run/postgresql"

- name: Set default privileges on database
  loop: "{{ schemes }}"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_privs:
    database: "{{ item.name }}"
    privs: ALL
    type: database
    role: "{{ item.username }}"
    login_unix_socket: "/var/run/postgresql"

- name: Change ownership of schema public to the user
  become: true
  become_user: "postgres"
  loop: "{{ schemes }}"
  community.postgresql.postgresql_owner:
    login_db: "{{ item.name }}"
    type: schema
    obj_name: public
    new_owner: "{{ item.username }}"
