#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/create_postgresql_users
- name: Refresh repos
  ansible.builtin.apt:
    update_cache: true
- name: Installing postgres
  become: true
  ansible.builtin.package:
    name: postgresql
    state: present

- name: Installing python3-psycopg2
  become: true
  ansible.builtin.package:
    name: python3-psycopg2
    state: present

- name: Creating database
  become: true
  become_user: "postgres"
  loop: "{{ schemes }}"
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    encoding: 'UTF-8'
    login_unix_socket : "/var/run/postgresql"
    state: present

- name: Creating user
  loop: "{{ schemes }}"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_user:
    db: "{{ item.name }}"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    login_unix_socket : "/var/run/postgresql"
    state: present

- name: Setting user's privileges on tables
  loop: "{{ schemes }}"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_privs:
    database: "{{ item.name }}"
    role: "{{ item.username }}"
    type: "table"
    privs: "ALL"
    objs: "ALL_IN_SCHEMA"
    login_unix_socket : "/var/run/postgresql"
    state: present

- name: Setting user's privileges on sequences
  loop: "{{ schemes }}"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_privs:
    database: "{{ item.name }}"
    role: "{{ item.username }}"
    type: "sequence"
    privs: "ALL"
    objs: "ALL_IN_SCHEMA"
    login_unix_socket : "/var/run/postgresql"
    state: present

- name: Setting user's privileges on functions
  loop: "{{ schemes }}"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_privs:
    database: "{{ item.name }}"
    role: "{{ item.username }}"
    type: "function"
    privs: "ALL"
    objs: "ALL_IN_SCHEMA"
    login_unix_socket : "/var/run/postgresql"
    state: present

- name: Setting user's privileges on procedures
  loop: "{{ schemes }}"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_privs:
    database: "{{ item.name }}"
    role: "{{ item.username }}"
    type: "procedure"
    privs: "ALL"
    objs: "ALL_IN_SCHEMA"
    login_unix_socket : "/var/run/postgresql"
    state: present

- name: Set default privileges on objects
  loop: "{{ schemes }}"
  become: true
  become_user: "postgres"
  community.postgresql.postgresql_privs:
    database: "{{ item.name }}"
    objs: ALL_DEFAULT
    privs: ALL
    type: default_privs
    role: "{{ item.username }}"
    grant_option: true