#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/create_postgresql_users
- name: Installing postgres
  become: true
  ansible.builtin.package:
    name: postgres
    state: present

- name: Creating database
  community.postgresql.postgresql_db :
    name: "postgres"
    encoding: 'UTF8'
    state: present

- name: Creating schemas
  with: "{{ schemes }}"
  community.postgresql.postgresql_schema :
    db: "postgres"
    name: "{{ item.name }}"
    state: present

- name: Creating users
  with: "{{ schemes }}"
  community.postgresql.postgresql_user:
    db: "postgres"
    role: "{{ item.username }}"
    password: "{{ item.username }}"
    state: present

- name: Setting user's privileges
  with: "{{ schemes }}"
  community.postgresql.postgresql_privs:
    database: "postgres"
    role: "{{ item.username }}"
    type: "schema"
    privs: "ALL"
    objs: "{{ item.name }}"
    state: present

