apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-certificate
spec:
  dnsNames:
  - 'apptest.ltillieu.duckdns.org'
  issuerRef:
    name: cert-manager-webhook-duckdns-production
    kind: ClusterIssuer
  secretName: ssl-certificate-secret