---
- name: Ensure curl is installed
  package:
    name: curl
    state: present

- name: Download Helm
  ansible.builtin.get_url:
    url: "{{ helm_url }}"
    dest: "/tmp/helm-{{ helm_version }}-linux-amd64.tar.gz"
    mode: '0644'

- name: Extract Helm
  ansible.builtin.unarchive:
    src: "/tmp/helm-{{ helm_version }}-linux-amd64.tar.gz"
    dest: "/tmp/"
    
    remote_src: yes

- name: Install Helm
  become: true
  ansible.builtin.command: 
    cmd: mv /tmp/linux-amd64/helm {{ helm_install_path }}
    creates: "{{ helm_install_path }}"  # This makes the task idempotent

- name: Clean up Helm tarball
  ansible.builtin.file:
    path: "/tmp/helm-{{ helm_version }}-linux-amd64.tar.gz"
    state: absent
