---
- name: Ensure curl is installed
  package:
    name: curl
    state: present

- name: Download Helm tarball
  get_url:
    url: "{{ helm_url }}"
    dest: "/tmp/helm-{{ helm_version }}-linux-amd64.tar.gz"
    mode: '0644'

- name: Extract Helm tarball
  unarchive:
    src: "/tmp/helm-{{ helm_version }}-linux-amd64.tar.gz"
    dest: "/tmp/"
    
    remote_src: yes

- name: Install Helm binary
  command: mv /tmp/linux-amd64/helm {{ helm_install_path }}
  creates: "{{ helm_install_path }}"  # This makes the task idempotent

- name: Clean up Helm tarball
  file:
    path: "/tmp/helm-{{ helm_version }}-linux-amd64.tar.gz"
    state: absent
