---

- name: Installing Sealed Secrets
  hosts: "{{ groups['k8s_controlplane'][0] }}"
  become: true
  tasks:
    - name:  Installing git
      become: true
      ansible.builtin.package:
        name: git
        state: present
        
    - name: Installing helm
      ansible.builtin.include_role:
        name: install_helm

    - name: Install helm-diff
      kubernetes.core.helm_plugin:
        plugin_path: https://github.com/databus23/helm-diff
        state: present
    
    - name: Adding sealed-secrets repo
      kubernetes.core.helm_repository:
        name: sealed-secrets
        repo_url: https://bitnami-labs.github.io/sealed-secrets

    - name: Installing sealed-secrets
      kubernetes.core.helm:
        name: sealed-secrets
        chart_ref: sealed-secrets/sealed-secrets
        release_namespace: kube-system
        create_namespace: true
        release_state: present
        wait: true
        timeout: "5m"
    
    - name: Importing private kube-system
      ansible.builtin.command:
        cmd: kubectl apply -f sealedsecret_private.key
    
    - name: Delete previous  pod
      ansible.builtin.command:
        cmd: kubectl delete pod -n kube-system -l app.kubernetes.io/name=sealed-secrets

