---

- name: Installing Sealed Secrets
  hosts: localhost
  tasks:
    - name:  Installing git
      become: true
      ansible.builtin.package:
        name: git
        state: present
        
    - name: Installing helm
      ansible.builtin.include_role:
        name: install_helm

    - name: Install helm-diff
      kubernetes.core.helm_plugin:
        plugin_path: https://github.com/databus23/helm-diff
        state: present
    
    - name: Adding sealed-secrets repo
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: https://bitnami-labs.github.io/sealed-private.key

    - name: Installing sealed-secrets
      kubernetes.core.helm:
        name: sealed-secrets
        chart_ref: sealed-secrets/sealed-secrets
        release_namespace: kube-system
        create_namespace: true
        state: present
        wait: true
        timeout: "5m"
    
    - name: Importing private kube-system
      kubernetes.core.k8s:
        state: patched
        src: ./sealedsecret_private.key

    - name: create resource using name generated by the server
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: Pod
          namespace: kube-system
          label_selectors: "app.kubernetes.io/name=sealed-secrets"

- name: Installing kubeseal
  hosts: k3s_server
  tasks:    
    - name: Install kubeseal
      ansible.builtin.command:
        cmd: |
          curl -OL "https://github.com/bitnami-labs/sealed-secrets/releases/download/v${KUBESEAL_VERSION}/kubeseal-${KUBESEAL_VERSION}-linux-amd64.tar.gz"
          tar -xvzf kubeseal-${KUBESEAL_VERSION}-linux-amd64.tar.gz kubeseal
          sudo install -m 755 kubeseal /usr/local/bin/kubeseal
      vars:
        KUBESEAL_VERSION: "0.28.0"
      

