---

- name: Install cert-manager
  hosts: "{{ groups['k8s_controlplane'][0] }}"
  become: true
  vars:
    ansible_python_interpreter: /opt/ansible_venv/bin/python3
  tasks:
    - name: Installing git
      become: true
      ansible.builtin.package:
        name: git
        state: present

    - name: Installing make
      become: true
      ansible.builtin.package:
        name: make
        state: present

    - name: Installing curl
      become: true
      ansible.builtin.package:
        name: curl
        state: present

    - name: Installing docker
      become: true
      ansible.builtin.package:
        name: docker.io
        state: present

    - name: Install helm-diff
      kubernetes.core.helm_plugin:
        plugin_path: https://github.com/databus23/helm-diff
        state: present

    - name: Adding jetstack repo
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io

    - name: Creating cert-manager namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: cert-manager

    - name: Installing cert-manager
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        create_namespace: true
        set_values:
          - value: crds.enabled=true
          - value: 'extraArgs={--dns01-recursive-nameservers=8.8.8.8:53\,1.1.1.1:53}'
        release_state: present
        wait: true
        timeout: "5m"

    - name: Check if cert-manager-webhook-duckdns Helm release exists
      kubernetes.core.helm_info:
        name: cert-manager-webhook-duckdns
        release_namespace: cert-manager
      register: duckdns_release
      ignore_errors: true

    - name: Cloning cert-manager-webhook-duckdns repo
      ansible.builtin.git:
        repo: https://github.com/ebrianne/cert-manager-webhook-duckdns.git
        dest: /tmp/cert-manager-webhook-duckdns
        force: true
      when: duckdns_release.failed or duckdns_release.status is undefined or duckdns_release.status == "FAILED"

    - name: Building cert-manager-webhook-duckdns
      community.general.make:
        chdir: /tmp/cert-manager-webhook-duckdns
        target: build
      when: duckdns_release.failed or duckdns_release.status is undefined or duckdns_release.status == "FAILED"

    - name: Installing cert-manager-webhook-duckdns
      kubernetes.core.helm:
        name: cert-manager-webhook-duckdns
        chart_ref: /tmp/cert-manager-webhook-duckdns/deploy/cert-manager-webhook-duckdns
        release_namespace: cert-manager
        create_namespace: true
        state: present
        wait: true
        timeout: "5m"
        set_values:
          - value: duckdns.token="{{ duckdns_token }}"
          - value: clusterIssuer.production.create=true
          - value: clusterIssuer.staging.create=true
          - value: clusterIssuer.email="{{ duckdns_email }}"
          - value: logLevel=2
      when: duckdns_release.failed or duckdns_release.status is undefined or duckdns_release.status == "FAILED"
