---
- name: Install requierements on all vm
  hosts: k8s
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        state: present
        name: "{{ item }}"
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - software-properties-common
        - gpg
        - open-iscsi
    - name: Start and enable iscsid
      ansible.builtin.systemd:
        name: iscsid
        state: started
        enabled: true
    - name: Disable swap for current session
      ansible.builtin.shell:
        cmd: swapoff -a
    - name: Disable swap for next sessions
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: ^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
        replace: '#\1\2\3swap\4'
    - name: Load required kernel modules
      community.general.modprobe:
        name: "{{ item }}"
        persistent: present
        state: present
      loop:
        - overlay
        - br_netfilter
    - name: Set network parameters
      ansible.posix.sysctl:
        state: present
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_file: /etc/sysctl.d/kubernetes.conf
        reload: true
      loop:
        - { name: 'net.bridge.bridge-nf-call-ip6tables', value: 1 }
        - { name: 'net.bridge.bridge-nf-call-iptables',  value: 1 }
        - { name: 'net.ipv4.ip_forward',                 value: 1 }
    - name: Install containerd
      ansible.builtin.package:
        state: present
        name: containerd
    - name: create containerd config directory
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
    - name: Copy containerd config file
      ansible.builtin.copy:
        src: ./files/containerd.toml
        dest: /etc/containerd/config.toml
    - name: restart containerd service
      ansible.builtin.systemd_service:
        name: containerd
        state: restarted
        enabled: true
    - name: delete kubernetes gpg key
      ansible.builtin.file:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: absent
    - name: Set kubernetes gpg key
      ansible.builtin.shell:
        cmd: 'curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg'
    - name: Add kubernetes repo
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /"  
        create: true
    - name: Refresh repos
      ansible.builtin.apt:
        update_cache: true
    - name: Install kubernetes packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - kubelet
        - kubeadm
        - kubectl
  
    
- name: Init cluster
  hosts: "{{ groups['k8s_controlplane'][0] }}"
  become: true
  tasks:
    - name: Check if a cluster is already installed
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: cluster_exists
    - name: Init cluster
      when: not cluster_exists.stat.exists
      ansible.builtin.command:
        cmd: "kubeadm init --control-plane-endpoint {{ k8s_loadbalancer_ip }} --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU"
    - name: Create .kube directory
      ansible.builtin.file:
        path: /root/.kube/
        state: directory
    - name: Copy kubernetes config file
      ansible.builtin.copy:
        remote_src: true
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
    - name: Get join cluster command
      ansible.builtin.command:
        cmd: "kubeadm token create --print-join-command"
      register: join_cluster_command
    - name: Get cluster certificates
      ansible.builtin.command:
        cmd: "kubeadm init phase upload-certs --upload-certs"
      register: join_cluster_certificate
    
    - name: Fails if cant get join command
      ansible.builtin.fail:
        msg: "Impossible to retreive command to join the cluster"
      when: join_cluster_command.rc != 0
    - name: Fails if cant get join command
      ansible.builtin.fail:
        msg: "Impossible to retreive certificates to join the cluster"
      when: join_cluster_certificate.rc != 0

- name: Join controlplanes to cluster
  hosts: "{{ groups['k8s_controlplane'][1:] }}"
  become: true
  tasks:
    - name: Check if a cluster is already installed
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: cluster_exists
    - name: Join controlplane
      when: not cluster_exists.stat.exists
      ansible.builtin.command:
        cmd: "{{ hostvars[groups['k8s_controlplane'][0]]['join_cluster_command'].stdout }} --ignore-preflight-errors=NumCPU --control-plane --certificate-key {{ hostvars[groups['k8s_controlplane'][0]]['join_cluster_certificate'].stdout_lines[-1] }}" 
    - name: Create .kube directory
      ansible.builtin.file:
        path: /root/.kube/
        state: directory
    - name: Copy kubernetes config file
      ansible.builtin.copy:
        remote_src: true
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config

- name: Join worker nodes to cluster
  hosts: "{{ groups['k8s_node'] }}"
  become: true
  tasks:
    - name: Check if a cluster is already installed
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: cluster_exists
    - name: Join worker
      when: not cluster_exists.stat.exists
      ansible.builtin.command:
        cmd: "{{ hostvars[groups['k8s_controlplane'][0]]['join_cluster_command'].stdout }} --ignore-preflight-errors=NumCPU" 

- name: Install helm on controlplane
  hosts: "{{ groups['k8s_controlplane'] }}"
  become: true
  tasks:
    - name: Remove helm gpg key
      ansible.builtin.file:
        path: /usr/share/keyrings/helm.gpg
        state: absent
    - name: Set helm gpg key
      ansible.builtin.shell:
        cmd: 'curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor -o /usr/share/keyrings/helm.gpg '
    - name: Add helm repo
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/helm-stable-debian.list
        line: "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"  
        create: true 
    - name: Refresh repos
      ansible.builtin.apt:
        update_cache: true
    - name: Install helm packages
      ansible.builtin.package:
        name: "helm"
        state: present

- name: Configure controlplanes to work with kubernetes modules
  hosts: "{{ groups['k8s_controlplane'] }}"
  become: true
  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name: python3-venv
    - name: Create python venv
      ansible.builtin.command:
        cmd: python3 -m venv /opt/ansible_venv
        creates: /opt/ansible_venv/bin/activate
    - name: Install pip modules
      ansible.builtin.pip:
        state: present
        name: "{{ item }}"
        virtualenv: "/opt/ansible_venv"
      loop:
        - kubernetes
        - jsonpatch
        - pyyaml



- name: Install required manifests
  hosts: "{{ groups['k8s_controlplane'][0] }}"
  become: true
  vars:
    ansible_python_interpreter: /opt/ansible_venv/bin/python3
  tasks:
    - name: Download manifests
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.path }}"
      loop:
        - {"url": "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml", "path": "/tmp/kube-flannel.yml"}
        - {"url": "https://raw.githubusercontent.com/longhorn/longhorn/v1.10.0/deploy/longhorn.yaml", "path": "/tmp/longhorn.yaml"}
    - name: Apply manifests
      kubernetes.core.k8s:
        src: "{{ item }}"
        state: present
      loop:
        - /tmp/kube-flannel.yml
        - /tmp/longhorn.yaml
    - name: copy longhorn service manifests
      ansible.builtin.copy:
        src: ./files/longhorn-service.yaml
        dest: /tmp/longhorn-service.yaml
    - name: Apply longhorn service manifests
      kubernetes.core.k8s:
        src: /tmp/longhorn-service.yaml
        state: present

        


