---
- name: Generating k3s token
  hosts: localhost
  tasks:
    - name: Generating token
      ansible.builtin.set_fact:
        k3s_token: "{{ lookup('community.general.random_string',length=32, min_special=1, override_special='?!;:.~()[]&%*') }}"
- name: Installing k3s
  hosts: k3s
  tasks:
    - name: Downloading k3s install script
      ansible.builtin.get_url:
        mode: u=rwx,g=rx,o=
        dest: /tmp/install_k3s.sh
        url: https://get.k3s.io

- name: Installing first master
  hosts: "{{ groups['k3s_server'][0] }}"
  tasks:
    - name: Check if k3s is already installed
      register: k3s_installed
      ansible.builtin.stat:
        path: /etc/rancher/k3s/k3s.yaml

    - name: Installing k3s
      changed_when: false # to improve
      ansible.builtin.command:
        cmd: "/tmp/install_k3s.sh --node-taint CriticalAddonsOnly=true:NoExecute --tls-san={{ k3s_proxy_server }}"
      environment:
        INSTALL_K3S_EXEC: "server"
        K3S_TOKEN: "{{ hostvars['localhost']['k3s_token'] }}"
        K3S_CLUSTER_INIT: true
      when: not k3s_installed.stat.exists
    - name: Save KUBECONFIG file
      become: true
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/k3s.yaml
        flat: true


- name: Installing masters
  hosts: "{{ groups['k3s_server'][1:] }}"
  gather_facts: true
  tasks:
    - name: Check if k3s is already installed
      register: k3s_installed
      ansible.builtin.stat:
        path: /etc/rancher/k3s/k3s.yaml

    - name: Installing k3s
      changed_when: false #to improve
      ansible.builtin.command:
        cmd: "/tmp/install_k3s.sh --node-taint CriticalAddonsOnly=true:NoExecute --tls-san={{ k3s_proxy_server }}"
      environment:
        INSTALL_K3S_EXEC: "server"
        K3S_TOKEN: "{{ hostvars['localhost']['k3s_token'] }}"
        K3S_URL: "https://{{ k3s_proxy_server }}:6443"
      when: not k3s_installed.stat.exists

- name: Installing agents
  hosts: k3s_node
  gather_facts: true
  tasks:
    - name: Check if k3s is already installed
      register: k3s_installed
      ansible.builtin.stat:
        path: /etc/rancher/k3s/k3s.yaml

    - name: Installing k3s
      changed_when: false #to improve
      ansible.builtin.command:
        cmd: /tmp/install_k3s.sh
      environment:
        INSTALL_K3S_EXEC: "agent"
        K3S_TOKEN: "{{ hostvars['localhost']['k3s_token'] }}"
        K3S_URL: "https://{{ k3s_proxy_server }}:6443"
      when: not k3s_installed.stat.exists

    - name: Installing nfs-common
      become: true
      ansible.builtin.package:
        name: nfs-common
        state: present
- name: Installing k9s
  hosts: 'k3s_server'
  tasks:
    - name: Check if k9s is already installed
      register: k9s_installed
      ansible.builtin.stat:
        path: /usr/bin/k9s

    - name: Downloading k9s deb file
      ansible.builtin.get_url:
        url: https://github.com/derailed/k9s/releases/download/v0.40.5/k9s_linux_amd64.deb
        dest: /tmp/k9s_linux_amd64.deb
      when: not k9s_installed.stat.exists

    - name: Installaling k9s
      become: true
      ansible.builtin.apt:
        deb: /tmp/k9s_linux_amd64.deb
      when: not k9s_installed.stat.exists

    - name: Configuring k9s
      become: true
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "export  KUBECONFIG=/etc/rancher/k3s/k3s.yaml"
        state: present

