---

- name: Install postgres
  hosts: 'postgres'
  gather_facts: true
  vars:
      no_logging: no
  tasks:
    - name: Create postgresql dbs
      ansible.builtin.include_role:
        name: init_postgresql_dbs
        
        
