name: Test GitHub
on: [push]
jobs:
    # Deploy_VMs:
    #     runs-on: self-hosted
    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v4

    #         - name: Setup Terraform
    #           uses: hashicorp/setup-terraform@v3

    #         - name: Authenticate to Google Cloud
    #           working-directory: ./terraform
    #           run: |
    #             echo '${{ secrets.GCP_CONNECTION_FILE }}' > ./gcloud-key.json
            
    #         - name: init terraform
    #           working-directory: ./terraform
    #           run:  terraform init
    #           env: 
    #             GOOGLE_APPLICATION_CREDENTIALS: "./gcloud-key.json"
            
    #         - name: Apply terraform
    #           working-directory: ./terraform
    #           run:  terraform apply -auto-approve
    #           env: 
    #             TF_VAR_gcp_bucket_name: ${{vars.GPC_BUCKET_NAME}}
    #             TF_VAR_terraform_private_key: ${{secrets.TERRAFORM_PRIVATE_KEY}}
    #             TF_VAR_proxmox_api_token: ${{secrets.PROXMOX_API_TOKEN}}
    #             TF_VAR_proxmox_ip: ${{secrets.PROXMOX_IP}}
    #             TF_VAR_proxmox_port: ${{secrets.PROXMOX_PORT}}
    #             TF_VAR_debian_url: ${{vars.DEBIAN_URL}}
    #             TF_VAR_debian_sha512: ${{vars.DEBIAN_SHA512}}
    #             TF_VAR_terraform_allowed_key_public: ${{secrets.TERRAFORM_ALLOWED_KEY_PUBLIC}}
    #             GOOGLE_APPLICATION_CREDENTIALS: "./gcloud-key.json"
    Install_k3s:
      runs-on: self-hosted
      # needs: [Deploy_VMs]
      container: 
        image: "ubuntu:22.04"
        options: --user root
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Installing python
          uses: actions/setup-python@v5
          with:
            python-version: '>=3.13' 

        - name: Installing git
          run: apt update && apt install -y git

        - name: Installing ansible
          uses: ansible/ansible-lint@main
          with: 
            setup_python: false
            working_directory: ./ansible
        
        - name: Set private Key file
          working-directory: ./ansible
          run: |
            echo ${{secrets.TERRAFORM_ALLOWED_KEY_PRIVATE}} > ansible_private_key
        
        - name: Install cluster
          working-directory: ./ansible
          run: ansible-playbook install_cluster.yaml
          env:
            terraform_allowed_key_private: ${{secrets.TERRAFORM_ALLOWED_KEY_PRIVATE}}
        

